# Generated by Django 3.2.7 on 2021-10-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='random_field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
