# Generated by Django 3.2.7 on 2021-10-22 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_userprofile_random_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='AdditionalUserDetails',
        ),
    ]
