# Generated by Django 3.2.7 on 2021-10-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211022_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalUserDetails',
        ),
    ]
