# Generated by Django 3.2.7 on 2021-10-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
