# Generated by Django 3.2.7 on 2021-10-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profile',
            new_name='user',
        ),
    ]
