# Generated by Django 3.2.7 on 2021-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.SmallIntegerField()),
                ('status_name', models.CharField(max_length=20)),
                ('status_description', models.TextField()),
            ],
        ),
    ]
