# Generated by Django 3.2.7 on 2021-10-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_orderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order Status'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='checkout.orderstatus'),
            preserve_default=False,
        ),
    ]
