# Generated by Django 3.2.7 on 2021-10-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20211024_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
