# Generated by Django 3.2.7 on 2021-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211007_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
