# Generated by Django 3.2.7 on 2021-10-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211021_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='from_price',
        ),
        migrations.AddField(
            model_name='category',
            name='headline',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
