# Generated by Django 3.2.7 on 2021-10-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211021_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category'),
        ),
    ]
